### ISSUE TITLE
Behavior of namespaces in imported classes

### ISSUE THREAD

**Issue by yzerlaut** [HumanBrainProject/fairgraph#33]
The following:
```
from fairgraph.client import KGClient
from fairgraph.brainsimulation import Person
client = KGClient()
yann = Person(family_name='Zerlaut',
              given_name='Yann')
yann.save(client)
```
raises a `namespace not set` error:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    yann.save(client)
  File "/home/yzerlaut/work/fairgraph/fairgraph/base.py", line 636, in save
    if self.id or self.exists(client, api="any"):
  File "/home/yzerlaut/work/fairgraph/fairgraph/base.py", line 544, in exists
    if self.exists(client, "nexus"):
  File "/home/yzerlaut/work/fairgraph/fairgraph/base.py", line 551, in exists
    response = client.query_nexus(self.__class__.path, query_filter, context)
  File "/home/yzerlaut/work/fairgraph/fairgraph/base.py", line 147, in path
    raise ValueError("namespace not set")
ValueError: namespace not set
```
Should one use systematically the `use_namespace` function ? Shouldn't it be set within the module ?

**Comment by apdavison** [comment]
this used to only apply (in v2) to classes that could be in multiple namespaces. Classes now all have a default KG space.
