### ISSUE TITLE
Organization field needs to be fixed

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/fairgraph#46]
Unable to edit BBP models in the model catalog.
Getting Internal Server Error.... tried via Python client and Dynamic Docs page as well

Traceback on server logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/docker/site/validation_service/resources/models.py", line 249, in update_model
    obj.save(kg_client)
  File "/usr/local/lib/python3.7/dist-packages/fairgraph/base.py", line 436, in save
    assert set(instance_type) == set(self.type), "{} != {}".format(set(instance_type), set(self.type))
AssertionError: {'a', ':', 'r', 'g', 't', 's', 'O', 'i', 'z', 'n', 'o'} != {'nsg:Organization'}
```
Getting errors even when simply trying to edit the model name,
But I don't get this error when trying to edit, for example, Rosanna's models

@apdavison had commented:
 The problem seems to be that fairgraph is expecting a list of types `[{'nsg:Organization'}]` and getting a dict `{'nsg:Organization'}`

**Comment by apdavison** [comment]
should no longer be a problem, with the switch to openMINDS
